import type { Lab } from "@/types/content";

// Real, live BodhiProtocol reference tools — the education/reference product
// line, distinct from the separate arcade-games portfolio.

export const labs: Lab[] = [
  {
    slug: "trade-lifecycle-explorer",
    title: "Trade Lifecycle Explorer",
    description: "Interactive walk-through of a trade from execution to settlement.",
    technology: ["HTML", "JS"],
    status: "live",
    difficulty: "intermediate",
    category: "Capital Markets",
    liveUrl: "https://bodhiprotocol.github.io/trade-lifecycle-explorer/",
    githubUrl: "https://github.com/BodhiProtocol/trade-lifecycle-explorer",
    roadmap: ["Add a failed-settlement / exception-handling walkthrough"],
  },
  {
    slug: "llm-wiki",
    title: "LLM Wiki",
    description: "24 core LLM concepts — tokens, prompting, RAG, embeddings, agents, MCP.",
    technology: ["HTML", "JS"],
    status: "live",
    difficulty: "beginner",
    category: "Artificial Intelligence",
    liveUrl: "https://bodhiprotocol.github.io/llm-wiki/",
    githubUrl: "https://github.com/BodhiProtocol/llm-wiki",
    roadmap: ["Expand coverage to evaluation and fine-tuning concepts"],
  },
  {
    slug: "regulatory-acronym-map",
    title: "Regulatory Acronym Map",
    description: "114 capital-markets regulatory terms across 10 categories, region-tagged.",
    technology: ["HTML", "JS"],
    status: "live",
    difficulty: "intermediate",
    category: "Capital Markets",
    liveUrl: "https://bodhiprotocol.github.io/regulatory-acronym-map/",
    githubUrl: "https://github.com/BodhiProtocol/regulatory-acronym-map",
    roadmap: ["Add APAC-specific regulatory coverage"],
  },
  {
    slug: "jargon-decoder",
    title: "Capital Markets Jargon Decoder",
    description: "Plain-English breakdowns of capital markets terminology with visual diagrams.",
    technology: ["HTML", "JS"],
    status: "live",
    difficulty: "beginner",
    category: "Capital Markets",
    liveUrl: "https://bodhiprotocol.github.io/jargon-decoder/",
    githubUrl: "https://github.com/BodhiProtocol/jargon-decoder",
    roadmap: ["Add audio pronunciations for common terms"],
  },
  {
    slug: "requirements-translator",
    title: "Requirements-to-User-Story Translator",
    description: "Turns raw business requirements into structured, testable user stories.",
    technology: ["HTML", "JS"],
    status: "live",
    difficulty: "intermediate",
    category: "Business Analysis",
    liveUrl: "https://bodhiprotocol.github.io/requirements-translator/",
    githubUrl: "https://github.com/BodhiProtocol/requirements-translator",
    roadmap: ["Add edge-case / acceptance-criteria prompts"],
  },
  {
    slug: "capital-markets-blueprint-explorer",
    title: "Capital Markets Blueprint Explorer",
    description: "All Capital Markets Lighthouse blueprints in one searchable, filterable view.",
    technology: ["HTML", "JS"],
    status: "live",
    difficulty: "beginner",
    category: "Capital Markets",
    liveUrl: "https://bodhiprotocol.github.io/capital-markets-blueprint-explorer/",
    githubUrl: "https://github.com/BodhiProtocol/capital-markets-blueprint-explorer",
    roadmap: ["Sync directly with this site's Project Lighthouse content"],
  },
  {
    slug: "business-analysis-blueprint-explorer",
    title: "Business Analysis Blueprint Explorer",
    description: "All Business Analysis Lighthouse blueprints in one searchable, filterable view.",
    technology: ["HTML", "JS"],
    status: "live",
    difficulty: "beginner",
    category: "Business Analysis",
    liveUrl: "https://bodhiprotocol.github.io/business-analysis-blueprint-explorer/",
    githubUrl: "https://github.com/BodhiProtocol/business-analysis-blueprint-explorer",
    roadmap: ["Sync directly with this site's Project Lighthouse content"],
  },
];

export function getAllLabs(): Lab[] {
  return labs;
}
