import type { Resource } from "@/types/content";

// Curated external reading. Every URL here was checked to resolve before being
// added — if a link rots, remove it rather than leaving a dead entry.
//
// `why` is the whole point of this page: a list of famous titles is a shopping
// list, not a library. The note is what makes it worth reading.

export const resources: Resource[] = [
  // ---------------------------------------------------------------- AI
  {
    title: "Attention Is All You Need",
    author: "Vaswani et al.",
    year: "2017",
    kind: "paper",
    category: "Artificial Intelligence",
    url: "https://arxiv.org/abs/1706.03762",
    why: "The paper that introduced the transformer — the architecture underneath essentially every modern LLM. Dense, but worth reading once precisely because so much is downstream of it.",
    free: true,
  },
  {
    title: "The Bitter Lesson",
    author: "Rich Sutton",
    year: "2019",
    kind: "essay",
    category: "Artificial Intelligence",
    url: "http://www.incompleteideas.net/IncIdeas/BitterLesson.html",
    why: "Two pages, and it reframes seventy years of AI research: methods that scale with compute keep beating methods that encode human cleverness. The single highest insight-per-word text on this list.",
    free: true,
  },
  {
    title: "Neural Networks: Zero to Hero",
    author: "Andrej Karpathy",
    kind: "course",
    category: "Artificial Intelligence",
    url: "https://karpathy.ai/zero-to-hero.html",
    why: "Builds a working LLM from an empty file, one line at a time. The rare course that leaves you with no black boxes — if you only do one thing to genuinely understand LLMs, do this.",
    free: true,
  },
  {
    title: "Neural Networks (visual series)",
    author: "3Blue1Brown",
    kind: "course",
    category: "Artificial Intelligence",
    url: "https://www.3blue1brown.com/topics/neural-networks",
    why: "The visual intuition to pair with Karpathy's code. Watch this first if the maths is what's blocking you — gradient descent stops being an equation and becomes a picture.",
    free: true,
  },
  {
    title: "Zoom In: An Introduction to Circuits",
    author: "Olah et al.",
    year: "2020",
    kind: "paper",
    category: "Artificial Intelligence",
    url: "https://distill.pub/2020/circuits/zoom-in/",
    why: "The founding text of mechanistic interpretability — the argument that you can actually open a neural network and read what it learned, rather than treating it as unknowable.",
    free: true,
  },
  {
    title: "Deep Learning",
    author: "Goodfellow, Bengio & Courville",
    year: "2016",
    kind: "book",
    category: "Artificial Intelligence",
    url: "https://www.deeplearningbook.org/",
    why: "The standard graduate reference, free to read online. Not a first book — but the one to reach for when you need the rigorous version of something you half-understand.",
    free: true,
  },

  // ---------------------------------------------------- Capital Markets
  {
    title: "Market Microstructure",
    author: "Wikipedia (overview)",
    kind: "reference",
    category: "Capital Markets",
    url: "https://en.wikipedia.org/wiki/Market_microstructure",
    why: "The map of the field that studies how trading actually happens — order books, spreads, price formation. Start here to find the vocabulary, then go read Harris properly.",
    free: true,
  },
  {
    title: "Flash Boys",
    author: "Michael Lewis",
    year: "2014",
    kind: "book",
    category: "Capital Markets",
    url: "https://en.wikipedia.org/wiki/Flash_Boys",
    why: "The most readable entry point into high-frequency trading and market structure. Contested by practitioners on the details — read it for the intuition, not as a verdict.",
    free: false,
  },
  {
    title: "When Genius Failed",
    author: "Roger Lowenstein",
    year: "2000",
    kind: "book",
    category: "Capital Markets",
    url: "https://en.wikipedia.org/wiki/When_Genius_Failed",
    why: "The LTCM collapse: Nobel laureates, flawless models, and near-systemic failure. The definitive case study in what leverage does to a model that was right on average.",
    free: false,
  },
  {
    title: "How Stock Markets Work",
    author: "US SEC (investor.gov)",
    kind: "reference",
    category: "Capital Markets",
    url: "https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work",
    why: "The regulator's own plain-English explainer. Worth knowing as a primary source — this is the baseline the rules are actually written against.",
    free: true,
  },
  {
    title: "MiFID II — Interactive Single Rulebook",
    author: "ESMA",
    kind: "reference",
    category: "Capital Markets",
    url: "https://www.esma.europa.eu/publications-and-data/interactive-single-rulebook/mifid-ii",
    why: "The actual regulation, navigable article by article. Most MiFID commentary is someone's summary of a summary — bookmark this and read the source when it matters.",
    free: true,
  },
  {
    title: "BIS Quarterly Review",
    author: "Bank for International Settlements",
    kind: "reference",
    category: "Capital Markets",
    url: "https://www.bis.org/publ/qtrpdf/r_qt2003.htm",
    why: "The central banks' central bank on what's actually moving in global markets. Denser than financial press, and correspondingly less wrong.",
    free: true,
  },

  // --------------------------------------------------- Business Analysis
  {
    title: "BABOK Guide",
    author: "IIBA",
    kind: "reference",
    category: "Business Analysis",
    url: "https://www.iiba.org/career-resources/a-business-analysis-professionals-foundation-for-success/babok/",
    why: "The profession's formal body of knowledge. Bureaucratic to read cover-to-cover, but it's the shared vocabulary — and knowing the official framing helps you argue with it.",
    free: false,
  },
  {
    title: "The Agile Manifesto",
    author: "Beck et al.",
    year: "2001",
    kind: "essay",
    category: "Business Analysis",
    url: "https://agilemanifesto.org/",
    why: "Sixty-eight words that reshaped how software gets specified. Read the original — almost everything sold as 'Agile' today is an elaboration nobody there signed off on.",
    free: true,
  },
  {
    title: "GOV.UK Service Manual — Agile Delivery",
    author: "UK Government Digital Service",
    kind: "reference",
    category: "Business Analysis",
    url: "https://www.gov.uk/service-manual/agile-delivery",
    why: "The most practical, least dogmatic delivery guidance published anywhere — written by a government that had to actually ship. Better than most paid consultancy material.",
    free: true,
  },
  {
    title: "Software Architecture Guide",
    author: "Martin Fowler",
    kind: "reference",
    category: "Business Analysis",
    url: "https://martinfowler.com/architecture/",
    why: "For the BA who wants to stop nodding along in architecture discussions. Fowler explains engineering tradeoffs in a way non-engineers can genuinely follow.",
    free: true,
  },

  // --------------------------------------------------- Decision Making
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    year: "2011",
    kind: "book",
    category: "Decision Making",
    url: "https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow",
    why: "The foundational text on how judgment actually works. Note: several priming studies in it failed to replicate — the core work on heuristics and biases holds, but read it knowing that.",
    free: false,
  },
  {
    title: "Superforecasting",
    author: "Tetlock & Gardner",
    year: "2015",
    kind: "book",
    category: "Decision Making",
    url: "https://en.wikipedia.org/wiki/Superforecasting",
    why: "The empirical answer to who predicts well and why. Its real lesson is procedural: forecasting is a trainable skill, and confident pundits are reliably worse at it than careful amateurs.",
    free: false,
  },
  {
    title: "Thinking in Bets",
    author: "Annie Duke",
    year: "2018",
    kind: "book",
    category: "Decision Making",
    url: "https://en.wikipedia.org/wiki/Annie_Duke",
    why: "A professional poker player on separating decision quality from outcome quality — the single most useful distinction for anyone judged on results they don't fully control.",
    free: false,
  },
  {
    title: "The Signal and the Noise",
    author: "Nate Silver",
    year: "2012",
    kind: "book",
    category: "Decision Making",
    url: "https://en.wikipedia.org/wiki/The_Signal_and_the_Noise",
    why: "Why most predictions fail, across weather, elections, and markets. The best popular introduction to thinking in probabilities rather than certainties.",
    free: false,
  },
  {
    title: "Decision Theory",
    author: "Stanford Encyclopedia of Philosophy",
    kind: "reference",
    category: "Decision Making",
    url: "https://plato.stanford.edu/entries/decision-theory/",
    why: "The rigorous foundation under the popular books — expected utility, risk versus uncertainty, where the axioms break. Free, and far more careful than anything on a bestseller list.",
    free: true,
  },

  // ------------------------------------------------------------ Economics
  {
    title: "The Use of Knowledge in Society",
    author: "Friedrich Hayek",
    year: "1945",
    kind: "paper",
    category: "Economics",
    url: "https://www.econlib.org/library/Essays/hykKnw.html",
    why: "The clearest argument ever made for what prices actually are: not values, but compressed signals carrying knowledge no single planner could hold. Short, and it rewires how you see markets.",
    free: true,
  },
  {
    title: "Thinking in Systems",
    author: "Donella Meadows",
    year: "2008",
    kind: "book",
    category: "Economics",
    url: "https://en.wikipedia.org/wiki/Donella_Meadows",
    why: "The best introduction to systems thinking there is — stocks, flows, feedback loops, and why well-intentioned interventions so often make things worse. The closest thing to this site's own thesis.",
    free: false,
  },
  {
    title: "Nudge",
    author: "Thaler & Sunstein",
    year: "2008",
    kind: "book",
    category: "Economics",
    url: "https://en.wikipedia.org/wiki/Nudge_(book)",
    why: "How choice architecture quietly shapes behaviour without removing options. Read it alongside the critiques — the replication record here is mixed, and that argument is instructive in itself.",
    free: false,
  },
  {
    title: "Misbehaving",
    author: "Richard Thaler",
    year: "2015",
    kind: "book",
    category: "Economics",
    url: "https://en.wikipedia.org/wiki/Misbehaving",
    why: "The story of how behavioural economics fought its way into a discipline built on the assumption that people are rational. Half memoir, half demolition of that assumption.",
    free: false,
  },
  {
    title: "Fooled by Randomness",
    author: "Nassim Nicholas Taleb",
    year: "2001",
    kind: "book",
    category: "Economics",
    url: "https://en.wikipedia.org/wiki/Fooled_by_Randomness",
    why: "On mistaking luck for skill — especially in markets, where survivors write the history. Abrasive by design, and more useful for it.",
    free: false,
  },
  {
    title: "Poor Economics",
    author: "Banerjee & Duflo",
    year: "2011",
    kind: "book",
    category: "Economics",
    url: "https://en.wikipedia.org/wiki/Poor_Economics",
    why: "Nobel-winning work on testing development policy with actual experiments rather than ideology. A masterclass in demanding evidence for claims everyone assumes are obvious.",
    free: false,
  },
];

export function getAllResources(): Resource[] {
  return resources;
}
