import {
  Brain,
  BookOpen,
  Coins,
  Compass,
  Cpu,
  Crown,
  Globe,
  Hand,
  Handshake,
  HeartHandshake,
  HeartPulse,
  Hourglass,
  Landmark,
  Layers,
  Lightbulb,
  MapPin,
  Plane,
  Radio,
  Scale,
  Shield,
  ShieldCheck,
  Target,
  TrendingUp,
  UserCog,
  Users,
  type LucideIcon,
} from "lucide-react";

// Shared icon-name lookup for Mental Models, Big Ideas, Enduring Influence, and
// Central Thesis cards across all Great Minds pages. Extend this map when a
// new figure's frontmatter references an icon name that isn't here yet.
const GREAT_MINDS_ICON_MAP: Record<string, LucideIcon> = {
  Brain,
  BookOpen,
  Lightbulb,
  Globe,
  Layers,
  TrendingUp,
  Scale,
  UserCog,
  MapPin,
  Landmark,
  Coins,
  Radio,
  Target,
  Hand,
  Crown,
  Shield,
  Users,
  Compass,
  HeartHandshake,
  Handshake,
  Hourglass,
  ShieldCheck,
  Plane,
  Cpu,
  HeartPulse,
};

export { GREAT_MINDS_ICON_MAP };
