import type { BlotterRecord, Outcome, Scenario } from "./types";

const outcomes: Outcome[] = [
  { id: "accepted", label: "Accepted", hint: "Goes through as requested." },
  { id: "rejected-state", label: "Rejected — state doesn't allow it", hint: "Nothing left to cancel or amend." },
  { id: "rejected-race", label: "Rejected — lost the race", hint: "OrderCancelReject: too late." },
  {
    id: "flagged-correction",
    label: "Not auto-processed — flagged as a correction",
    hint: "No true delete; becomes a reviewed, linked record.",
  },
];

const decoyRows: BlotterRecord[] = [
  {
    idLabel: "ClOrdID",
    id: "ORD-4461",
    instrument: "HDFC Bank",
    side: "Buy",
    qty: 800,
    cumQty: 800,
    leavesQty: 0,
    status: "Filled",
    lastPrice: "₹1,642.10",
  },
  {
    idLabel: "ClOrdID",
    id: "ORD-4465",
    instrument: "Nifty 50 Fut",
    side: "Sell",
    qty: 25,
    cumQty: 0,
    leavesQty: 25,
    status: "New",
    lastPrice: "₹24,880.00",
  },
  {
    idLabel: "TradeID",
    id: "TRD-9021",
    instrument: "7.18% GOI 2033",
    side: "Sell",
    qty: 5000000,
    cumQty: 5000000,
    leavesQty: 0,
    status: "Settled",
    lastPrice: "101.250",
  },
];

const scenarios: Scenario[] = [
  {
    id: "cancel-resting",
    label: "Resting order",
    desk: "Equities — NSE",
    record: {
      idLabel: "ClOrdID",
      id: "ORD-4471",
      instrument: "Infosys",
      side: "Buy",
      qty: 500,
      cumQty: 0,
      leavesQty: 500,
      status: "New",
      lastPrice: "₹1,550.00",
    },
    requestType: "Cancel",
    requestDetail: "Trader wants to withdraw the full 500-share order before any of it has traded.",
    requestedBy: "Trading desk",
    correctOutcome: "accepted",
    log: [
      { time: "10:42:07.184", kind: "sent", text: "OrderCancelRequest 35=F  ClOrdID=ORD-4471", tone: "muted" },
      {
        time: "10:42:07.201",
        kind: "received",
        text: "ExecutionReport 35=8  ExecType=4 (Canceled)  OrdStatus=4 (Canceled)",
        tone: "brand",
      },
    ],
    explanation:
      "Nothing has filled yet — OrdStatus is still New. A cancel on a fully resting order is the simplest, cleanest case: the order is withdrawn and confirmed with ExecType=4.",
    essay: {
      href: "/essays/cancel-amend-delete-what-changes-the-moment-a-trade-executes",
      label: "Cancel, Amend, Delete",
    },
  },
  {
    id: "cancel-race",
    label: "Losing the race",
    desk: "Equities — NSE",
    record: {
      idLabel: "ClOrdID",
      id: "ORD-4472",
      instrument: "TCS",
      side: "Buy",
      qty: 500,
      cumQty: 200,
      leavesQty: 300,
      status: "PartiallyFilled",
      lastPrice: "₹3,912.50",
    },
    requestType: "Cancel",
    requestDetail: "Trader cancels the remaining 300 shares — at the exact instant the exchange fills them.",
    requestedBy: "Trading desk",
    correctOutcome: "rejected-race",
    log: [
      { time: "11:03:44.552", kind: "sent", text: "OrderCancelRequest 35=F  ClOrdID=ORD-4472", tone: "muted" },
      {
        time: "11:03:44.553",
        kind: "received",
        text: "ExecutionReport 35=8  ExecType=F (Trade)  OrdStatus=2 (Filled)",
        tone: "brand",
      },
      {
        time: "11:03:44.560",
        kind: "received",
        text: "OrderCancelReject 35=9  Reason=Too late to cancel",
        tone: "destructive",
      },
    ],
    explanation:
      "The fill and the cancel request crossed in flight. The exchange doesn't silently drop the losing cancel — it sends a separate OrderCancelReject, distinct from the ExecutionReport that reports the fill.",
    essay: {
      href: "/essays/fix-messages-order-status-is-a-state-execution-type-is-an-event",
      label: "FIX Messages: OrdStatus vs. ExecType",
    },
  },
  {
    id: "amend-below-filled",
    label: "Amend below filled",
    desk: "Fixed Income",
    record: {
      idLabel: "ClOrdID",
      id: "ORD-4473",
      instrument: "Reliance Industries",
      side: "Sell",
      qty: 1000,
      cumQty: 600,
      leavesQty: 400,
      status: "PartiallyFilled",
      lastPrice: "₹2,910.00",
    },
    requestType: "Amend Qty",
    requestDetail: "Desk tries to amend total order quantity down to 500 — but 600 have already filled.",
    requestedBy: "Trading desk",
    correctOutcome: "rejected-state",
    log: [
      {
        time: "12:15:09.310",
        kind: "sent",
        text: "OrderCancelReplaceRequest 35=G  OrderQty=500",
        tone: "muted",
      },
      {
        time: "12:15:09.318",
        kind: "received",
        text: "OrderCancelReject 35=9  Reason=OrderQty below CumQty (600)",
        tone: "destructive",
      },
    ],
    explanation:
      "An amend can reprice or resize the unfilled remainder, but it can never reach back and un-fill quantity that's already executed. 500 is below the 600 already filled — a hard reject, not something the exchange leaves for downstream systems to catch.",
    essay: {
      href: "/essays/cancel-amend-delete-what-changes-the-moment-a-trade-executes",
      label: "Cancel, Amend, Delete",
    },
  },
  {
    id: "amend-filled",
    label: "Amend a filled order",
    desk: "Equities — NSE",
    record: {
      idLabel: "ClOrdID",
      id: "ORD-4474",
      instrument: "HDFC Bank",
      side: "Buy",
      qty: 200,
      cumQty: 200,
      leavesQty: 0,
      status: "Filled",
      lastPrice: "₹1,644.30",
    },
    requestType: "Amend Price",
    requestDetail: "Junior dealer tries to amend the limit price after the order has already fully filled.",
    requestedBy: "Trading desk",
    correctOutcome: "rejected-state",
    log: [
      { time: "13:27:52.001", kind: "sent", text: "OrderCancelReplaceRequest 35=G  Price=1640.00", tone: "muted" },
      {
        time: "13:27:52.004",
        kind: "received",
        text: "OrderCancelReject 35=9  Reason=OrdStatus=2 (Filled) — nothing to amend",
        tone: "destructive",
      },
    ],
    explanation:
      "LeavesQty is 0 — there's no resting quantity left for an amend to act on. The system rejects it before it's even worth sending to the exchange.",
    essay: {
      href: "/essays/cancel-amend-delete-what-changes-the-moment-a-trade-executes",
      label: "Cancel, Amend, Delete",
    },
  },
  {
    id: "duplicate-cancel",
    label: "Duplicate cancel",
    desk: "Equities — NSE",
    record: {
      idLabel: "ClOrdID",
      id: "ORD-4475",
      instrument: "Wipro",
      side: "Sell",
      qty: 1500,
      cumQty: 0,
      leavesQty: 1500,
      status: "PendingCancel",
      lastPrice: "₹289.40",
    },
    requestType: "Cancel",
    requestDetail: "A second cancel is sent for the same order — the first cancel hasn't confirmed yet.",
    requestedBy: "Trading desk",
    correctOutcome: "rejected-state",
    log: [
      { time: "14:02:18.442", kind: "sent", text: "OrderCancelRequest 35=F  ClOrdID=ORD-4475b", tone: "muted" },
      {
        time: "14:02:18.446",
        kind: "received",
        text: "OrderCancelReject 35=9  Reason=OrdStatus=6 (Pending Cancel) — request already in flight",
        tone: "destructive",
      },
    ],
    explanation:
      "OrdStatus=6, Pending Cancel, means a cancel is already working. A second cancel on top of it isn't harmless — it's rejected so two in-flight requests can't race each other and confirm out of order.",
    essay: {
      href: "/essays/fix-messages-order-status-is-a-state-execution-type-is-an-event",
      label: "FIX Messages: OrdStatus vs. ExecType",
    },
  },
  {
    id: "delete-settled-trade",
    label: "“Delete” a settled trade",
    desk: "Post-trade — Ops",
    record: {
      idLabel: "TradeID",
      id: "TRD-8834",
      instrument: "ICICI Bank",
      side: "Buy",
      qty: 2000,
      cumQty: 2000,
      leavesQty: 0,
      status: "Settled",
      lastPrice: "₹1,208.75",
    },
    requestType: "Delete",
    requestDetail: "Ops asks the system to “delete” a trade that's already confirmed and settled.",
    requestedBy: "Post-trade operations",
    correctOutcome: "flagged-correction",
    log: [
      { time: "15:40:03.117", kind: "sent", text: "DeleteTrade  TradeID=TRD-8834", tone: "muted" },
      {
        time: "15:40:03.119",
        kind: "info",
        text: "No delete operation exists on a confirmed trade record.",
        tone: "destructive",
      },
      {
        time: "15:40:03.130",
        kind: "received",
        text: "TradeCorrection created  RefID=TRD-8834  New linked record=TRD-8834-C1",
        tone: "brand",
      },
    ],
    explanation:
      "A settled trade is never erased — the audit trail has to stay provable. What Ops actually gets is a new, linked correction record referencing the original, not a deletion.",
    essay: {
      href: "/essays/cancel-amend-delete-what-changes-the-moment-a-trade-executes",
      label: "Cancel, Amend, Delete",
    },
  },
  {
    id: "legit-correction",
    label: "Same-day correction",
    desk: "Post-trade — Ops",
    record: {
      idLabel: "TradeID",
      id: "TRD-8840",
      instrument: "Larsen & Toubro",
      side: "Sell",
      qty: 750,
      cumQty: 750,
      leavesQty: 0,
      status: "Settled",
      lastPrice: "₹3,580.00",
    },
    requestType: "Correct",
    requestDetail: "Dealer keyed the wrong settlement account 11 minutes after execution — genuine punching error, fixed same day, reason code attached.",
    requestedBy: "Trading desk",
    correctOutcome: "accepted",
    log: [
      {
        time: "09:51:14.004",
        kind: "sent",
        text: "TradeCorrectionRequest  RefID=TRD-8840  Reason=Wrong SSI, dealer input error",
        tone: "muted",
      },
      {
        time: "09:51:14.021",
        kind: "received",
        text: "TradeCorrection accepted  New linked record=TRD-8840-C1",
        tone: "brand",
      },
    ],
    explanation:
      "Timing and a genuine reason code make the difference. Filed minutes after execution, before any outcome could be known, this sails through as an ordinary correction.",
    essay: {
      href: "/essays/the-correction-that-isnt-cancel-amend-and-money-laundering",
      label: "The Correction That Isn't",
    },
  },
  {
    id: "suspicious-correction",
    label: "Correction, no reason given",
    desk: "Post-trade — Ops",
    record: {
      idLabel: "TradeID",
      id: "TRD-8851",
      instrument: "Adani Ports",
      side: "Buy",
      qty: 4000,
      cumQty: 4000,
      leavesQty: 0,
      status: "Settled",
      lastPrice: "₹1,412.60",
    },
    requestType: "Correct",
    requestDetail:
      "A client-code change is requested six hours after execution, once the position is known to be profitable — no reason code attached.",
    requestedBy: "Trading desk",
    correctOutcome: "flagged-correction",
    log: [
      {
        time: "16:12:47.900",
        kind: "sent",
        text: "ClientCodeModification  RefID=TRD-8851  Reason=(none provided)",
        tone: "muted",
      },
      {
        time: "16:12:47.905",
        kind: "info",
        text: "Modification rate + no stated reason breaches auto-approval threshold.",
        tone: "destructive",
      },
      {
        time: "16:12:47.910",
        kind: "received",
        text: "Routed to compliance review — not applied automatically",
        tone: "destructive",
      },
    ],
    explanation:
      "Same mechanism as the last case, opposite outcome. A late correction with no genuine-error reason and a favorable outcome already visible is exactly the pattern client-code-modification abuse runs on — it gets held for review, not waved through.",
    essay: {
      href: "/essays/the-correction-that-isnt-cancel-amend-and-money-laundering",
      label: "The Correction That Isn't",
    },
  },
];

export { outcomes, decoyRows, scenarios };
